version: '3.3'

services:
  plantuml-server:
    build:
      context: .
      dockerfile: Dockerfile.jetty
      args:
        BASE_URL: plantuml
    image: plantuml/plantuml-server:ssl7
    container_name: plantuml-server
    ports:
      - 8089:8080
      - 9095:9095
    volumes:
      - "${HOME}/.m2:/root/.m2"